var relearn_search_index=[{breadcrumb:"Cantara > Tutorial",content:`Background Story When I was at my high school time, I became part in the leadership of a Christian youth group. When conducting our events, we liked to sing a few songs at the beginning. However the problem occurred that the available song books where not enough and the content was sometimes not matching with the songs which were wished. At that time I was looking for an available song presentation program and became disappointed quickly. Most of the existing programs were either commercial, very complicated or simply an “overkill” for the basically quite simple purpose: People should be able to (spontaneously) choosing songs, the program should then display them.
At that time, I decided to start the development of Cantara. The name is coming from the Latin “cantare” (to sing) but more artificial then real. An other reason for choosing the name was that at the same time, I was becoming an organ player in church –and the German name for that position is “Kantor” which sounds quite similar.
Later I have been able to lead the best student group in the world 😃 and while doing so, the program slowly was growing and updated with new futures like multi-screen-support and the opportunity to export song texts directly to the clipboard so that it can be used in small groups without beamer projection possibility. Cantara’s development will continue and I hope that it will be a small tool to praise and worship our great heavenly father!
The Approach graph LR; A[Input File] -->|Collecting Songs| B(Song List) B --> C(Song Selection) C --> D{Generate Presentation Data} D --> E[Run Presentation Directly] D --> F[Export Lyrics in Markup Format] D --> G[Export Presentation as PPTX] D --> H[Export Presentation as Pictures] Cantara takes the songs from one particular folder on the file system which is called the song repository (or briefly song repo). Every song is a simple text file which can be edited with a text editor of your choice. Cantara will recognize the song title from the name of the file (without the extension). So, for example. If you have a file like:
Amazing Grace.song Cantara will recognize it as “Amazing Grace” written in the song format (for formats see the next section).
Tip The song repository dictionary can be shared and synced easily via cloud services like NextCloud or Git. In that way you can distribute songs within your group or organization.
Tip Since version 2.4.0, Cantara offers a built-in editor which you can use to edit the songs and convert CCLI songs to the Cantara song format. Notice that the songs remain single text files and therefore can still be edited with any text editor.
Warning The developers of Cantara are not responsible for copyright issues which come along with the public use and distributions of song lyrics. Make sure that you obtain the rights for using the song lyrics! In Germany, religious gatherings with free admission enjoy higher copyright freedom than commercial events. However, please make sure with your organization that no legal problems arise.
The windows/modes of Cantara Cantara consists of different windows which allow you to use the program.
Windows Song Selection Window Presentation Window Presentation Controller Settings Editor This windows will be displayed after you start Cantara. It allows you to see the songs which are available and select those which you would like to use in the presentation or to export. The presentation window will show and control the loaded presentation (in single screen mode). It can be set to full screen and moved to an other screen. If you close the presentation window, the presentation will end and you will return to the song selection window. In multi screen mode, the presentation controller allows you to control the presentation in detail which is shown at the presentation window. You can see all slides, jump to a slide directly or quit the presentation. Normally, you would place the presentation controller on the first screen (the default screen) and the presentation window at the second screen (which is displayed at the beamer, external monitor, etc.). Tip The presentation controller uses the song selection window.
The settings window allows you to adjust the presentation style and change the path of the song repository. You can open the settings in the song selection window. The editor allows to add, modify, convert and remove songs in your song repository. You can open the editor via Edit -> Song Lyrics... in the song selection window. `,description:"Background Story When I was at my high school time, I became part in the leadership of a Christian youth group. When conducting our events, we liked to sing a few songs at the beginning. However the problem occurred that the available song books where not enough and the content was sometimes not matching with the songs which were wished. At that time I was looking for an available song presentation program and became disappointed quickly.",tags:[],title:"How Cantara Works",uri:"/tutorial/how-cantara-works/index.html"},{breadcrumb:"Cantara > Contribute",content:`Cantara can be easily translated to an other language. While doing so, you will help to spread the use of the software all over the world, so that also people who don’t speak English have access to Cantara.
How it works Cantara uses language files (*.mo-files) which contain the translated language strings in a binary language. This files can be created by using an editor like Poedit using the cantara.pot file as a template.
If you would like to do a translation into a new language, procedure in the following way:
Download cantara.pot and open it with an appropriate editor.
Translate the strings into the desired target language.
Export the translated content as an .mo-file but also keep the translated .po file!
Copy the language.mo file to <cantara-dir>/languages/language/cantara.mo (replace language with the shortcode of the language, e.g. de for German, en for English, zh for Chinese, etc.).
Test your translation by running Cantara with the --lang option:
cantara --lang=<language code>
If the translation works well, please make a pull request at GitHub so that others can make use of it as well.
Current State Currently, Cantara is translated to the following languages:
Language Completeness English 100 % German 100 % Chinese (traditional) 100 % Italian 100 % Spanish 100 % Dutch 100 % `,description:`Cantara can be easily translated to an other language. While doing so, you will help to spread the use of the software all over the world, so that also people who don’t speak English have access to Cantara.
How it works Cantara uses language files (*.mo-files) which contain the translated language strings in a binary language. This files can be created by using an editor like Poedit using the cantara.pot file as a template.`,tags:[],title:"Translate",uri:"/contribute/translate/index.html"},{breadcrumb:"Cantara",content:`This page contains information about the changes in different versions (releases) and plans for the future.
Releases Version 2.6.0 (2024-05-31) Migrate to bgrabitmap for better handling and displaying of the presentation slides. In the future, further text effects like shadows etc. can be easily implemented. Redesign the multi screen presentation controller: In addition to the songs, every slide with content is listed and can be selected directly. Context menu of presentation window: Fullscreen and ending of presentation is now also selectable with that menu. Minor improvements of the song editor and full text search. Add “Select all Songs” under File menu in song selection. Bugfix: Wrong display of presentation when no specific font has been selected #24 Bugfix: Drag and Drop exception in song selection window Bugfix: Wrong escaping of special characters in pptx-export A lot of minor bugfixes and corrections Translation update Version 2.5.0 (2023-08-21) Complete rewriting of large parts of the source code including the internal structures for generating and painting presentation slides Improvement of the presentation layout Improvement of the song editor Implementation of a preview of the presentation in the settings menu Implementation of slide export to pptx (using PptxgenJs) Implementation of slide export to pictures Implementation of song lyrics export to markup text files Implementation of a full text search for browsing song lyrics Implementation of a two language song presentation Improvements of the presentation window and control (more keys and remote controls are supported) Fix issue #17 Cantara can now be directly opened with a .songtex-file. Version 2.4.1 (2023-01-30) Italian and Spanish translation The version 2.4.1. adds Italian and Spanish translation to Cantara. Despite that, there is no additional functionality compared to Version 2.4.0 which means that if you are not using one of the languages, you don’t necessarily need to update to this version.
Thank you to the translators!
The Italian translation has been provided by @albanobattistella The Spanish translation has been provided by @haggen88 Thank you for the effort!
Version 2.4.0 (2023-01-06) Version 2.4 is finally there! Beside new features, it also brings a lot of bug fixes. See the list below for details.
Improvements/Enhancements A new editor has been implemented which allows editing of the songs, converting CCLI songs into the song format, creating new songs, archiving them and cloning them (e.g. for different versions). A welcome assistant will guide new users after the first start of Cantara to setup and understand the program. Cantara can automatically break long slides into two pages if configured in the settings. The newly implemented SongTeX file format allows to export songs slides with the song lyrics and the order. Bug Fixes Floating point errors when no background picture was selected Loading the slides took a long time if a background was selected Version 2.3.2 (2022-11-10) This is a minor release which brings two small but useful improvements:
Completion of traditional Chinese translation readiness for Flatpak Check the corresponding GitHub page for details.
Version 2.3.1 (2022-08-12) This is a minor release and follow up on version 2.3
Improvements Version 2.3.1 brings support for background images. These can be adjusted and made transparent (towards the background color) or brighter. Bug Fixes fix of spell mistake in CCLI license tag. It is now ccli-licensenumber complete German translation Version 2.3 (2022-08-02) After testing and further development, version 2.3 can be released.
Improvements:
Support of the CCLI songselect format* Support for Metadata which can be displayed dynamically during the song Improvements in source code Preparations for further development in source code, abstractions Bugfixes in displaying the songs As always, I am looking forward to feedback, suggestions and bug reports. Thank you!
Go to Github page of the Release`,description:`This page contains information about the changes in different versions (releases) and plans for the future.
Releases Version 2.6.0 (2024-05-31) Migrate to bgrabitmap for better handling and displaying of the presentation slides. In the future, further text effects like shadows etc. can be easily implemented. Redesign the multi screen presentation controller: In addition to the songs, every slide with content is listed and can be selected directly. Context menu of presentation window: Fullscreen and ending of presentation is now also selectable with that menu.`,tags:[],title:"Release Notes",uri:"/releasenotes/index.html"},{breadcrumb:"Cantara",content:`Starting with Cantara is very easy and can be done while following this three steps:
Download Cantara Collect Songs Run and configure Cantara While a detailed explanation with download links can be found in the Tutorial Section, this page just contains some short advises.
Download Cantara There are several download links for different operation systems.
Go to the Download and Installation Tutorial Section for further information. Check out the Releases Page on Github for further options. Collect Songs Use services like CCLI Song Select or other databases to get lyrics for the songs which you want to sing! You don’t know where to start? Take a look here.
Run and configure Cantara The configuration of Cantara should be self-explanatory for most of the cases. If you need further information, you can head to the tutorial section, too.`,description:`Starting with Cantara is very easy and can be done while following this three steps:
Download Cantara Collect Songs Run and configure Cantara While a detailed explanation with download links can be found in the Tutorial Section, this page just contains some short advises.
Download Cantara There are several download links for different operation systems.
Go to the Download and Installation Tutorial Section for further information. Check out the Releases Page on Github for further options.`,tags:[],title:"Quick Start",uri:"/quick-start/index.html"},{breadcrumb:"Cantara > Tutorial",content:`This page describes how you can install Cantara on your local operating system.
Windows Installation on Windows is very easy and done in just one minute. You can either use the Windows package manager Winget or download and run the installer manually.
Using winget (Windows 10 and Windows 11) If you are running one of the modern versions of Windows (Windows 10 1709 or later), you can use Winget to install Cantara safely and keep it up to date. Simply open a Windows Powershell and run the following command:
winget install cantaraWinget will download the installer, ask you once for confirmation and afterwards runs the installer silently. If a new version gets published, you can update via winget upgrade --all or winget upgrade cantara.
If you would like to remove Cantara from your system, you can run winget uninstall cantara.
Running the installer If you don’t like to use winget, you can also download and run the installer manually which will lead you through the process of installation.
Simply download and run the installer, go through the questions and install Cantara. After the installation, you will find the program in your start menu. In addition, if you have chosen the option during the setup process, you will also have a shortcut on your desktop.
Info When starting the installer, Windows might warn you that the source is unknown and the executable unsigned. In this case, you can choose “Proceed” to continue. This is due to the fact that I don’t own a certificate which I could use for certification of the executable. However as the software has been published to Winget, you can safely install it from there and without seeing this notification.
Linux Cantara was developed by a Linux fan and enthusiast. So, it is my pleasure to make sure that Cantara is working well on every Linux distribution.
Info Cantara can use the Qt6, QT5 and GTK2 librarys for the graphical user interface. Depending on the distribution channel, Cantara is precompiled with Qt6 or Qt5-bindings. If you prefer GTK2, please compile cantara by yourself.
Arch Linux and Arch based distributions (Manjaro, Garuda, etc.) The Arch User Repository (AUR) The Arch User Repository (AUR) contains package built information which allows you to build software packages automatically and install them on your local file system. This is the prefered way for installation of software outside of the official repositories. There are two Cantara package builds in the AUR: Use cantara-bin for a pre-compiled version of Cantara and cantara if you would like the system to compile the package. Note that for the installation process of the second option, the compilers and libraries of Pascal and Lazarus have to get downloaded and installed which might require several hundred megabytes of disk space. You can delete these tools after the compilation process has been completed.
There are many ways how to install a package from the AUR. Most people might use a helper like yay. Just install one of the packages:
yay cantara-bin # fast and compact installation of pre-compiled binary yay cantara # downloads source code and compile by yourself Note A big advantage of using a helper like yay is that it will also keep the packages up-to-date! Whenever a new version of Cantara gets released, you should be able to update it via sudo yay -Syu
Once installed, Cantara can be uninstalled via pacman: sudo pacman -R cantara.
Pre-Built Pacman Installation Package If you don’t like to use the AUR, you can also use the pre-built Pacman package from the Github repository. For downloading and installing the package, simply enter the following commands in the command line:
wget https://github.com/reckel-jm/cantara/releases/download/v2.6.0/cantara-2.6.0-1-x86_64.pkg.tar.zst sudo pacman -U cantara-2.6.0-1-x86_64.pkg.tar.zstCantara is now installed and ready for use. If you later would like to uninstall it, you can use Pacman as well:
sudo pacman -R cantaraUbuntu/Debian based Linux distributions Please use Snap or Flatpak as described in the concerning sections.
Snap Cantara is available at the Snap Store! The snap package now only takes 4.5 MB and is therefore a good distribution-independent way to install Cantara. You can follow the instructions on the Cantara store page to find out how to install it on your local system or - if snapd is already running - install it via the command line.
sudo snap install cantara Info The way how a Snap application is running is different from a normal package. Therefore there might be some different behavior e.g. a different look of the program. In any case, feel free to report every unexpected behavior so that I can try to fix it.
Snap will create a starter in the start menu. If you like to run Cantara via the command line, the command is snap run cantara.
Tip You can also install different versions of Cantara at the same time and even install Cantara as a classical package and a snap together. Check the Snap Documentation for further details.
Flatpak/Flathub Cantara has been packaged as a Flatpak as well and can be installed and updated from flathub.org. This requires an installed flatpak on your operation system. Some distribution like Fedora have this already out of the box, in other distributions like Arch Linux, you need to install it manually.
Installing a flatpak from flathub can be done via a graphical software management tool, for example Gnome Software or KDE Discover, or via the command line:
flatpak install app.cantara.CantaraDepending on the flats you have already installed, flatpak might download several houndreds of megabytes for the required KDE/Qt-runtimes. That being said, although the actual Cantara flat is less then 4 MB installing Cantara via flatpak is for sure not the most disk space friendly way.
Generic Run of Binaries Warning Installing Cantara without using your native package manager or a containerized format (Snap/Flatpak) is strongly discouraged and not recommended. Use this only for locally running Cantara without installation.
As an other distribution-independant way of using Cantara, you can manually download and run the binary. Please be aware that Cantara needs the libqt5pas library which is normally resolved by the package dependancy management of your distribution’s package manager. However, if you don’t use the package manager for installation, you need to install libqt5pas manually. Afterwards, download the Zip-File from the Github Repository, extract it, make the binary executable and run cantara:
wget https://github.com/reckel-jm/cantara/releases/download/v2.6.0/cantara-2.6.0-linux-x86_64_bin.tar.gz tar -zxvf cantara-2.6.0-linux-x86_64_bin.tar.gz cd cantara-2.6.0-linux-x86_64_bin chmod +x cantara ./cantaraGeneric Compilation Install lazarus and lazbuild from your local repository. If you prefer QT5, you could also install lazarus-qt instead of lazarus if the distribution provides a certain package. After you have done that, the compilation is quite easy: Download the source code, extract it and run lazbuild with the appropriate options.
wget https://github.com/reckel-jm/cantara/archive/refs/tags/v2.6.0.tar.gz tar -zxvf v2.6.0.tar.gz cd v2.6.0 makeIf you prefer GTK2, change the option to --ws=gtk2 in the makefile. If done with no errors, you will find the executable binary cantara in the same folder.
Mac OS Cantara is working on Mac OS X. However, it has not been officially certified which means that you can not install it in a normal way yet. Please follow these steps to use Cantara:
Download the Cantara Mac OS X binary from Github. Open the zip-Archive in Finder so that it will exttract the content to a folder. Open a terminal and navigate to the Folder, for example with cd Downloads/cantara-2.6.0-macosx if you are using the default Download folder. When you are in the extracted folder, make the binary file executable with chmod +x src/cantara.app/Contents/cantara Run the binary with ./src/cantara.app/Contents/cantara. Cantara should start now. You can attach it to the dock so that you can open it easily again. `,description:`This page describes how you can install Cantara on your local operating system.
Windows Installation on Windows is very easy and done in just one minute. You can either use the Windows package manager Winget or download and run the installer manually.
Using winget (Windows 10 and Windows 11) If you are running one of the modern versions of Windows (Windows 10 1709 or later), you can use Winget to install Cantara safely and keep it up to date.`,tags:[],title:"Install Cantara",uri:"/tutorial/install-cantara/index.html"},{breadcrumb:"Cantara > Contribute",content:`Cantara would not have been possible without the help of the following contributors (GitHub users in alphabetical order):
@reckel-jm: Main development and maintaining @freundTech: helping with preparing the program for flatpak @primores-resugendi: Contributing traditional Chinese translation @albanobattistella: Contributing Italian translation @haggen88: Contributing Spanish translation @vistaus: Contributing Dutch translation Thank you very much!`,description:`Cantara would not have been possible without the help of the following contributors (GitHub users in alphabetical order):
@reckel-jm: Main development and maintaining @freundTech: helping with preparing the program for flatpak @primores-resugendi: Contributing traditional Chinese translation @albanobattistella: Contributing Italian translation @haggen88: Contributing Spanish translation @vistaus: Contributing Dutch translation Thank you very much!`,tags:[],title:"Contributors",uri:"/contribute/contributors/index.html"},{breadcrumb:"Cantara > Tutorial",content:`First Steps After the installation, simply open Cantara with your start menu or the cantara command. You will then see the welcome assistent which helps you to go through the configuration of Cantara. Here you should choose a song repository directory where you all the song lyrics files are stored. If you have none yet, you can create an empty new folder and select it as your song repository. The assistent will suggest you to add “Amazing Grace” as an example song which you can use to understand how the program works.
After you have finished the welcome assistent, you should also adjust the font settings, the text color or the background color according to your wishes. You can do that in the Settings (Edit -> Settings). The option Spoiler next Slide will show the lyrics of the next song part in smaller font size under the current part.
Beside that, you can configure how the Meta Data of songs should be displayed. See more details in the section Meta Data.
The Song Selection Window If the configuration has been done successfully, you will come to the song selection window where you can choose the songs which you would like to sing. The search field may help you to find the one you like. Simply double-click or press enter after the selection of the song in the left list, and the song will go to the right list where you can adjust the order or remove the selected songs. After you are done, press the Presentation button to start the presentation. You can also press CTRL+P instead.
Tip Cantara will automatically detect at start whether you have connected a second monitor (like a second screen or a beamer) to your PC. If so, it will select the two-windows-mode automatically. You can also adjust this as you want.
During the Presentation Mode During the presentation mode, you can control the presentation slides via several ways:
Using the arrow keys: You can use the arrow keys of your keyboard to go forward or backwardF Pressing F5/F11: this will toggle fullscreen Using the Enter or Space key: You can use Enter or Space for moving a slide forward Pressing ESC: will end the presentation Mouse Click: Will move a slide forward Clicking at a song at the right selection list in the song selection window (multi screen-mode only): You can directly jump to a certain song Tip If you are running other programs like Libreoffice Impress or MS PowerPoint in presentation mode at the same time, you can easily switch between the presenters with Alt+Tab. When the presentation mode in Cantara gets started, it will cover the second screen and be in foreground. To move Cantara to the background, press Alt+Tab to navigate to the program you want to show up.
Adjust the Presentation After you have seen the default presentation style, you might want to adjust it according to your wishes and needs. For this, you can open the settings dialog (Edit -> Settings). There you can set up the following:
Song Repo Path: The path of the song repository. Use the button with the three points (..) in order to select a file chooser dialog. Empty Slides between songs: This creates an additional empty slide in the presentation between two different songs. Spoil next slides: Displays the content or parts of of the next slide below the text if the song has an additional slide and the space of the slide is sufficient. Alignment: Adjust the horizontal and vertical alignment of the text in the presentation slides. Press Details to set up the border size. Automatic word wrap: Brakes the slides into if one stanza (song part) has reached the specified limit of lines (recommended especially if you have songs with long stanzas). Change Font Settings…/Background Color…/Text Color…: Opens dialogs for specifing the design of the presentation. Background Image: Opens a file chooser dialog where you can select a background image for your presentations. If available, the folder with some default background pictures will be opened at first. Change Image Transparancy: Adjusts the image transparency towards the background color. That means if the background color is (for example) set to black, a higher value will make the picture darker. If the background would be white, a higher value will make the picture brighter. Show Meta Data: Certain Meta data can be shown at a special title slide (if choosen), at the first slide or at the last slide. Enter the syntax in the big edit field at the bottom and see Meta Data for detalis. Preview image: Click at the preview to go one slide forward. If the presentation has reached its end, it will go back to the beginning. Export Presentation Cantara offers several ways for exporting presentations so that they can be reused in an other program or for an other purpose. All the export options are available in the export menu of the main window. Generally, there are two types of exports:
Export the presentation slides: This will export the presentation slides exactly as they are displayed inside Cantara. At the moment there are two export options for this type: Power Point Presentation (.pptx-file): This will export the slide presentation as a pptx file so that it can be used in a presentation program (Microsoft Powerpoint, Libreoffice Impress, Softmaker Presentation etc.). For the generation of the slides, the JavaScript library PptxGenJs (MIT license) will be used inside the local web browser as a renderer. Pictures/Images: This will export a JPEG file for every slide and save it into a folder of choice. Export the Lyrics as Markup: It will export the lyrics of the songs in their right order in a specified markup format but without any presentation settings (slide breaks, background picture, colors, etc.). This can be used (but is not limited) for: Exporting the songs as a WhatsApp/Telegram message so that it can be shared a long groups/channels for the congregation/people to sing along Exporting the songs as a HTML webpage so they can be published on a webpage Exporting just the titles of the song so they can be reported to CCLI. The structure of the markup can be specified through a LaTeX style markup language. Go to Export -> Markup Text To open the Markup Export window.
The template language supports the following commands/environments. All of them are optional:
\\header { ... }: The header part of the document which will be shown at the top of the document. No song specific content can be displayed here as this part is outside of the song loop. \\footer { ... }: The footer part of the document which will be shown at the bottom of the document. No song specific content can be displayed here as this part is outside of the song loop. \\newline: Inserts a system default line break \\betweensongs { ... }: Defines what should be displayed between two songs (but not before the first song and after the last song). The default value is set to two line breaks (a new paragraph: \\betweensongs { \\newline \\newline }) \\lineending: Specifies the line ending inside the song loop (default value is \\newline) \\songloop { ... } The content which will be displayed for each song (repeated for each song). Inside this environment, song tags (see Meta Data) can be accessed via \\tagname – for example \\title for the title tag and \\author for the author tag. The lyrics itself a loaded via the \\lyrics command. Save and Load Song Selections You can save and load song selections into Cantara to share it within the organization or for preparing an event. While doing so, you have two options:
The songtex-format contains the song names and the song file with its content. That means, if you export the songselection to a songtex-file, the receiver don’t need to have the songs in his song repository. While importing the songtex-file, Cantara checks whether the file already exists in the repository, and, if not, adds it. The legacy export/import function imports only the titles, that means, the receiver needs to have the songs in his song repository. `,description:"First Steps After the installation, simply open Cantara with your start menu or the cantara command. You will then see the welcome assistent which helps you to go through the configuration of Cantara. Here you should choose a song repository directory where you all the song lyrics files are stored. If you have none yet, you can create an empty new folder and select it as your song repository. The assistent will suggest you to add “Amazing Grace” as an example song which you can use to understand how the program works.",tags:[],title:"General Usage",uri:"/tutorial/how-to-use-it/index.html"},{breadcrumb:"Cantara",content:`The following pages will give you a detailed instruction to Cantara and how the software works. For most users, Cantara should work well out of the box. However, if there are problems or issues which can’t be solved, feel also free to go to the Github repository and ask for additional help.
Info Please note that this tutorial is for version 2.5.0 and later. Prior versions won’t support all the features which are described in this section.
While reading the following pages, you will be able to learn how Cantara works, how you can download it, where you can get song lyrics from and how you can use the program.
The author is always looking forward for feedback and recommendations. Thank you!`,description:`The following pages will give you a detailed instruction to Cantara and how the software works. For most users, Cantara should work well out of the box. However, if there are problems or issues which can’t be solved, feel also free to go to the Github repository and ask for additional help.
Info Please note that this tutorial is for version 2.5.0 and later. Prior versions won’t support all the features which are described in this section.`,tags:[],title:"Tutorial",uri:"/tutorial/index.html"},{breadcrumb:"Cantara",content:`Cantara is a volunteer project and therefore offers no professional support. However, the developer is very happy to help if there are any questions or troubles. The preferred way of contact would be to open a GitHub issue.
GitHub is a free software collaboration platform. You can easily create an account there and then open an issue with your question or the problem which you have.`,description:`Cantara is a volunteer project and therefore offers no professional support. However, the developer is very happy to help if there are any questions or troubles. The preferred way of contact would be to open a GitHub issue.
GitHub is a free software collaboration platform. You can easily create an account there and then open an issue with your question or the problem which you have.`,tags:[],title:"Get Help",uri:"/get-help/index.html"},{breadcrumb:"Cantara > Tutorial",content:`When using Cantara, you will need to collect, edit and distribute songs which can be used for presenting or exporting. If you start Cantara for the first time, you will notice that–depending on what you have chosen in the welcome assistent–you might only find one song available: “Amazing Grace”. From that point on, you can start to get and add songs.
The folder which you choose two be your song repository will contain all the songs which you use in Cantara. That means that in order to add a new song, it is enough to just add a new file in that folder. Likewise you might proceed for editing or deleting songs. If you want to share all songs with someone else, just copy the files of your dictionary or share the folder itself. It has been also developed as a common pratice to create a Git repository in your repository folder which than can be shared via Github, Gitlab or other providers.
Understanding the way how songs are saved Cantara supports two different song formats. One has the file ending .song and is very simply designed. It just contains the lyrics in the order as they should be presented along with some tags which describe the meta data of the songs. The other format is used by CCLI Songselect and has the file endings .txt or .ccli. CCLI is a commercial database where you can download a lot of Christian songs for the use in churches or Christian groups.
Tip A lot of Christian church denominations and groups in Germany (including FeG, SMD as far as I know) provide member access to CCLI Songselect. You can find out whether you organization has already booked a subscription for you.
Cantara will automatically detect the correct song format and interpretate it in the way as stated below.
The song file format The song file format is a file which ends with .song. The lyrics there have to be printed in the same order as they should be shown including repetitions. Different slides are seperated with a double linebreak (an empty line). For example, if you would like to add the song “‘Tis so sweet to trust in Jesus”, add a new file 'Tis so sweet to trust in Jesus.song with the following content:
Expand the file content 'Tis so sweet to trust in Jesus Just to take Him at His word Just to rest upon His promise Just to know thus saith the Lord Jesus Jesus how I trust Him How I've proved Him o'er and o'er Jesus Jesus precious Jesus O for grace to trust Him more O how sweet to trust in Jesus Just to trust His cleansing blood Just in simple faith to plunge me 'Neath the healing cleansing flood Jesus Jesus how I trust Him How I've proved Him o'er and o'er Jesus Jesus precious Jesus O for grace to trust Him more Yes 'tis sweet to trust in Jesus Just from sin and self to cease Just from Jesus simply taking Life and rest and joy and peace Jesus Jesus how I trust Him How I've proved Him o'er and o'er Jesus Jesus precious Jesus O for grace to trust Him more I'm so glad I learned to trust Thee Precious Jesus Savior Friend And I know that Thou art with me Wilt be with me to the end Jesus Jesus how I trust Him How I've proved Him o'er and o'er Jesus Jesus precious Jesus O for grace to trust Him more The song consists of four stanzas with the chorus repeated after each one. Now, let’s say that we would like to have a slightly different version of the song where we sing two stanzas together. A good convention fot this would be to copy the existing file 'Tis so sweet to trust in Jesus.song to 'Tis so sweet to trust in Jesus [two stanzas together].song and adjust the content:
Expand the file content 'Tis so sweet to trust in Jesus Just to take Him at His word Just to rest upon His promise Just to know thus saith the Lord O how sweet to trust in Jesus Just to trust His cleansing blood Just in simple faith to plunge me 'Neath the healing cleansing flood Jesus Jesus how I trust Him How I've proved Him o'er and o'er Jesus Jesus precious Jesus O for grace to trust Him more Yes 'tis sweet to trust in Jesus Just from sin and self to cease Just from Jesus simply taking Life and rest and joy and peace I'm so glad I learned to trust Thee Precious Jesus Savior Friend And I know that Thou art with me Wilt be with me to the end Jesus Jesus how I trust Him How I've proved Him o'er and o'er Jesus Jesus precious Jesus O for grace to trust Him more Cantara will detect both song files and list them next to each other. While this approach seems to be a little bit complecated at the beginning, the practical usage has shown that it is much easier then using more complex file formats. You can always use your local text editor to adjust the lyrics as you like them to be. There will be no danger of missinterpretation or wrong order.
CCLI Songselect The CCLI songselect format will be used if you download a song from CCLI songselect. In opposite to the song format, the CCLI songselect lyrics format provides no clear information about the correct order of the different parts in a song (stanzas/choruses etc.). So, Cantara has to guess the order with an implemented algorithm. For most of the songs, Cantara will put the lyrics into the correct order. However, some of the CCLI song files lack consistency. In this case, you can convert the CCLI file to a song file and manually edit it according to your needs.
Note Due to the lack of consitency, it is not recommended to edit a CCLI songselect file directly. Cantara will ask you to convert it to a song file first.
Here is some information about the parts which Cantara does understand:
“Vers/Strophe”: a stanza which will be sung only once at the placed position “Chorus”: if available, the chorus will be sung at the placed position and afterwards repeated after every stanza or bridge. If an other chorus will come, it will replace the first one. “Bridge”: Will be treated like a stanza. A chorus will (most likely) follow if there has been one before. “PreChorus”: Will be sung before chorus (here the format is quite inconsistent!) “Schluss”: A closing part of the song. No chorus will follow. Note The editor is capable of converting CCLI files to the song format. Just open a CCLi file in the editor and confirm that you would like to perform the conversion.
Download songs from CCLI Songselect As stated above, you can directly import songs from CCLI Songselect. Go to their webpage, login with your account and search for the song which you want to download. Press the speech bubble symbol right next to it (see picture below). After the text is shown, click at the third blue button from the left with the download symbol. Save the .txt-file directly into the Cantara song repository directory. Cantara should recognize the song and use the lyrics in the correct order.
Warning As stated before, it is your responsability to comply with the legal requirements of CCLI and the song copyright owners when using their services!
Additional Song Lyrics Sources Hymnary.org: A very large hymn collection (mostly English) Evangeliums.net: A German collection of Christian songs, some can not be accessed directly due to copyright restrictions The Cantara SongRepo at Github: Contains Public Domain Songs for free and direct use Edit and convert songs with the built-in editor Cantara offers a built-in editor which provides an easy way to create songs, edit them or remove them. In addition, you can convert a CCLI song to the song format so that it might be adapted to your needs.`,description:`When using Cantara, you will need to collect, edit and distribute songs which can be used for presenting or exporting. If you start Cantara for the first time, you will notice that–depending on what you have chosen in the welcome assistent–you might only find one song available: “Amazing Grace”. From that point on, you can start to get and add songs.
The folder which you choose two be your song repository will contain all the songs which you use in Cantara.`,tags:[],title:"Manage Songs",uri:"/tutorial/where-to-get-the-songs/index.html"},{breadcrumb:"Cantara > Tutorial",content:`Cantara allows you to fetch and display meta data from the songs. Depending on the song format, Cantara will get the following meta data.
CCLI Songselect Following data will be collected from each CCLI songselect lyrics file:
author: The name(s) of all author(s) separated by a ‘|’. ccli-licensenumber: The number of the CCLI license which is dependent on the user account (not on the song) ccli-songnumber: The CCLI number on the song which is dependent on the song. Song format In the song format, meta data can be specified by a line with a # at the beginning. For example:
#author: John Newton #title: Amazing Grace Amazing Grace, how sweet the sound that saved a wretch like me. I once wast lost, but now am found, was blind, but now I'm free! [...] This will set the meta data for author and title.
How to use the meta data: In the settings dialog, you can enable meta data for each song. In the Meta Data Content field, you can specify the format how meta data should be displayed. Beside showing plain text, you can use the following variables:
{property1}: Will show the meta data property property1 if it exists. {%property1%}some text{%end%}: Will show some text if property1 exists. {%property1%}some text: Will show some text (till the end of the line) if *property1 exists. For example, the following syntax:
{%ccli-licensenumber%}Song Source: CCLI {ccli-licensenumber} {%author%}Author: {author} Would generate for the above Amazing Grace.song:
Author: John Newton because author exists but ccli-licensenumber does not.`,description:`Cantara allows you to fetch and display meta data from the songs. Depending on the song format, Cantara will get the following meta data.
CCLI Songselect Following data will be collected from each CCLI songselect lyrics file:
author: The name(s) of all author(s) separated by a ‘|’. ccli-licensenumber: The number of the CCLI license which is dependent on the user account (not on the song) ccli-songnumber: The CCLI number on the song which is dependent on the song.`,tags:[],title:"Song Meta Data",uri:"/tutorial/meta-data/index.html"},{breadcrumb:"Cantara",content:`Cantara is free Software and has been developed with a lot of patience and passion. If you like it, I would be grateful if you consider one of the things below. Thank you for using Cantara. It is my pleasure and honor!
Give feedback, recommendations and bug reports If you find any issues, have ideas or recommendations or want to report a bug, please open an issue at the Cantara Github repository. I work completely via Github on the project, so that would be the best way to go. If you have no Github account and don’t want to create one, ask a friend to do it for you.
Translate Cantara to an other language Cantara is used by people all over the world. Over the time, some volunteers contributed translations to several languages. Take a look at the translation section to learn the current state of the art and ways how to support me in this matter.
Recommend it The more people use Cantara, the better the program can get! Feel free to recommend Cantara via your available channels.
Don’t donate to me, but to someone else The author of Cantara has the privilege of holding a full time job and therefore has no need or desire of a financial support at the moment. Therefore, donations for Cantara aren’t needed for now. However, there are a lot of people in the world who are currently really in need or suffering. If you like Cantara and you find that while using the software you have saved some money, please consider to support one of the non-profit-organisations below which I really appreciate and want to support:
OpenDoors: A Christian organization helping persecuted Christians all over the world. Missioneswerk Werner Heukelbach: A missionary organization for sharing the gospel in Germany. Support Ukraine by donating to NGOs, the Red Cross or other Ukrainian organizations, and help the country and its people to preserve its freedom and existence! Thank you for your help!`,description:`Cantara is free Software and has been developed with a lot of patience and passion. If you like it, I would be grateful if you consider one of the things below. Thank you for using Cantara. It is my pleasure and honor!
Give feedback, recommendations and bug reports If you find any issues, have ideas or recommendations or want to report a bug, please open an issue at the Cantara Github repository.`,tags:[],title:"Contribute",uri:"/contribute/index.html"},{breadcrumb:"Cantara",content:`In this section, some articles about Cantara will get published from time to time.
Published Artcles February 2nd: The General Roadmap of the Project `,description:`In this section, some articles about Cantara will get published from time to time.
Published Artcles February 2nd: The General Roadmap of the Project `,tags:[],title:"Blog",uri:"/blog/index.html"},{breadcrumb:"Cantara > Blog",content:`When I started Cantara six years ago (three years before I created this Github repository), I didn’t except that I would continue the project for such a long time. Originally only designed for my personal purpose (having a simple song presentation program for church groups) it is now a widely used Open Source project. According to the snap store statistics (which is the only reliable one I have at the moment), Cantara is currently used by more then 120 individuals from 39 countries around the world. In addition to that, there are AUR, Flatpak and Windows users from which I don’t have any statistical data. Cantara has been translated into Chinese, Italien, Spanish and German by the community and whenever when I get some feedback, I am really happy to see how this little program can be a tool to serve the church for the honor of God. With that being said, I would like to introduce some ideas and plans which I have for the future of the program and I am interested in your thoughts and suggestions as well:
Cantara as a presentation program and presentation provider A lot of churches have a complex presentation workflow for their church services/events which includes song presentations, presentations for the sermon (provided by the preacher), videos, Bible readings, announcements, etc. Although there are all-in-one-solutions who are designed for addressing all of this purposes, they are often lacking in functionality compared to the “original” ones. For example, a lot of sermons will be designed in PowerPoint, Libre Office Impress, LaTeX beamer or any other presentation software. It is unlikely that Cantara–even if we would try–could ever get the same functionality as these programs. However, Cantara could be a provider to such workflows if it allows to export the song presentations in these formats. Therefore I am planning to add an export functionality which allows to generate presentations which can be imported into other programs for getting a unified workflow experience. At the moment, my idea is as following:
PowerPoint presentations can be easily created via the PptxGenJS-library which is published under the MIT license. We could use the systems web browser to run the JavaScript and in that way keep Cantara leightweight. Cantara would need to export the presentations into some JavaScript code which can be used by the web browser + PptxGenJS to create a pptx. In addition to that, I would like to provide export options into revealJs and LaTeX Beamer slides which are also widely used and Open Source which is definitely an important reason to support these. I would love to use the Libre Office format (odp). However I don’t know any library/framework which could be used to generate such files. If anyone has some hints for me, feel free to share. This is all of course in addition to the presentation functionality and not as a replacement. The users will have the choice whether they would like to use Cantara as a song presentation tool or whether they would like to use it to generate the presentations which an be embedded into their presentation program of choice.
Generate Sheets and Chords for the Musicians An other long time desired feature would be to extend the musical functionality of Cantara so that the software could also generate sheets PDFs for the musicians. For that, I would prefer a combination of LuaLaTeX, Lilypond and lyluatex which allows the generation of nice song books. The idea is that in addition to the song lyrics, song sheets (either an ly-file or a pdf file) can be managed as well. If a song presentation is created, Cantara would be also able to generate the sheets and put them into one PDF file so that the musicians don’t need to look for the sheets by themselves.
An alternative approach would be a JavaScript framework such as OpensheetmusicDisplay. This would require the source files to be in MusicXML instead of Liilypond and would not allow complete PDFs to be imported.
Migrating to Flutter? Pascal is an amazing programing language for development and Lazarus is very good for platform independent programing. However, with the time going forward there are other widely supported alternatives as well. One of them is Flutter which has been developed by Google. It would allow to create one application for all (Windows, Linux, Mac OS, Android, iOS). Whether it fits or not, could be evaluated in the future, so that maybe a long term migration to Flutter could be an option (but does not have to).
Time Roadmap Due to private circumstances, development will be continued after April 2023. Till that time, I have to finish my master thesis and collect more ideas and plans :-)
Any ideas, comments or thoughts? Continue the discussion on Github`,description:"When I started Cantara six years ago (three years before I created this Github repository), I didn’t except that I would continue the project for such a long time. Originally only designed for my personal purpose (having a simple song presentation program for church groups) it is now a widely used Open Source project. According to the snap store statistics (which is the only reliable one I have at the moment), Cantara is currently used by more then 120 individuals from 39 countries around the world.",tags:[],title:"The General Roadmap of the Project",uri:"/blog/2023-02-01-the-general-roadmap-of-the-project/index.html"},{breadcrumb:"Cantara",content:`Imprint This site is run by:
Jan Martin Reckel
Jollystraße 73 76137 Karlsruhe
Use GitHub for any software related contact request.
The content of this webpage is provided as it is without any warranty or assurance that the information might be correct. The author takes no responsibility for external links or references.
Data Privacy For this Webpage This webpage has no contact form or any function implemented which would save or track user data. No analytic tools are used. The webpage provider does not set any cookies.
The webpage is hosted at GitHub pages with the following address:
GitHub Inc.
88 Colin P Kelly Jr St
San Francisco, CA 94107
United States
GitHub might collecting the following logging data when accessing this webpage:
IP address address of previously visited webpage data and time of the request time zone difference to GMT content of the request HTTP status code browser and operation system information amount of transferred data We have no access to this data and will therefore not use them in any purpose.
If you are using GitHub for pull requests, submitting issues etc., their data privacy regulations apply.
For the program Cantara Cantara does not collect or submit any data. The configuration is saved locally on your file system. Cantara does not connect to the internet. It doesn’t commit or use any sort of tracking.`,description:`Imprint This site is run by:
Jan Martin Reckel
Jollystraße 73 76137 Karlsruhe
Use GitHub for any software related contact request.
The content of this webpage is provided as it is without any warranty or assurance that the information might be correct. The author takes no responsibility for external links or references.
Data Privacy For this Webpage This webpage has no contact form or any function implemented which would save or track user data.`,tags:[],title:"Imprint and Data Privacy",uri:"/imprint/index.html"},{breadcrumb:"",content:`Welcome to this webpage!
Cantara is a song presentation software which can be used for presenting songs in churches, small groups or karaoke parties. It supports various input formats and can create beautiful presentation slides or export the presentation to various output formats (pictures, pptx, WhatsApp message and a lot more) so that they can be used for a variety of purposes. Cantara has the following advantages:
Super-fast and lightweight: Cantara is less then 10 MB of size and uses the components available on the local operation system as far as possible. It contains no bloatware. It can be run on an old computer, a raspberry-pi and many more. Very easy to use: Accepts the most common input format (CCLI songselect lyrics file) and creats the presentation slides for an event in only a few seconds. The usage is very intuitive and user-friendly. Good integration with other presentation software: Cantara can export presentations to PPTX format and therefore integrates easily with other presentation software like LibreOffice Impress or MS Powerpoint. It can be included in a complex workflow like a church service or even an online streaming event via OBS. In addition, you can export the lyrics to text formats and share them in messenger groups, as a HTML page etc. Multi-Screen-Support: Multi Screen is supported out of the box. Customizable Design and good outlook: The colors and fonts can be configured in the settings. In addition, you can set up a background picture and adjust it’s brightness/transparency. The presentations look beautiful and are easy to read. Multi language support: Cantara can present and export song presentations in two different languges at the same time. In addition, it has been translated itself into a few languages by the community. Free and Open Source: No license fees, no dependence on certain companies–Cantara is licensed under the GPL3 and can be used everywhere and as you want. Used all over the world and continuously developed: Although Cantara is still a quite young project, people from many countries are using it. It has been translated to several langauges. In the future, more functions are going to be implemented. The current version is 2.6.0. You can easily download and install it for Linux, Windows and Mac OS. Cantara is written with the programming language Pascal/Lazarus, therefore it is platform-independent and can be compiled to almost every device. You can also compile Cantara by yourself. Find more information here.`,description:`Welcome to this webpage!
Cantara is a song presentation software which can be used for presenting songs in churches, small groups or karaoke parties. It supports various input formats and can create beautiful presentation slides or export the presentation to various output formats (pictures, pptx, WhatsApp message and a lot more) so that they can be used for a variety of purposes. Cantara has the following advantages:
Super-fast and lightweight: Cantara is less then 10 MB of size and uses the components available on the local operation system as far as possible.`,tags:[],title:"Cantara",uri:"/index.html"},{breadcrumb:"Cantara",content:"",description:"",tags:[],title:"Categories",uri:"/categories/index.html"},{breadcrumb:"Cantara",content:"",description:"",tags:[],title:"Tags",uri:"/tags/index.html"}]